# Generated by Django 4.2.5 on 2023-10-04 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
