# Generated by Django 4.2.5 on 2023-10-06 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
